export const DB_HOST = <YOUR_DATABASE_HOST>;
export const DB_USER = <YOUR_DATABASE_USERNAME>;
export const DB_PASSWORD = <YOUR_DATABASE_PASSWORD>;
export const DB_NAME = <YOUR_DATABASE_TABLE_NAME>;
export const EC2_URL = 'http://<YOUR_EC2_PUBLIC_IP:YOUR_EC2_PUBLIC_PORT>/posts' <>;